In [35]:
import numpy as np

a = np.array([[22, 5, 16, 9], [13, 20, 19, 0], [5, 9, 1, 16], [27,13,15,19]])
b = np.array([[10,5,20,20], [5,21,22,27], [26,19,22,3], [27,8,18,7]])
c = np.array([24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20])
d = np.array([3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6])

one = a + b
two = a - b
three = a * b
four = np.dot(a,b)
five = c+d
six = c-d
seven = c*d
eight = np.dot(c,d)
nine = a+10
ten = b+10
eleven = c+15
twelve = d+15
thirteen = (2*a) + (2*b)
fourteen = (a + b) * 3
fifteen = (a-b+a-b) * 4

print('1. ', one)
print('2. ', two)
print('3. ', three)
print('4. ', four)
print('5. ', five)
print('6. ', six)
print('7. ', seven)
print('8. ', eight)
print('9. ', nine)
print('10. ', ten)
print('11. ', eleven)
print('12. ', twelve)
print('13. ', thirteen)
print('14. ', fourteen)
print('15. ', fifteen)

1.  [[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]
2.  [[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]
3.  [[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]
4.  [[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]
5.  [27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]
6.  [ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]
7.  [ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]
8.  2298
9.  [[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]
10.  [[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]
11.  [39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]
12.  [18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]
13.  [[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]


In [12]:
print ('hello')

hello
